In [2]:
import pandas as pd

cashflows = pd.read_excel('Cashflows.xlsx')

In [5]:
cashflows.describe()

,FUND ID,FIRM ID,VINTAGE / INCEPTION YEAR,FUND SIZE (USD MN),TRANSACTION DATE,TRANSACTION AMOUNT,CUMULATIVE CONTRIBUTION,CUMULATIVE DISTRIBUTION,NET CASHFLOW,QUARTILE,TARGET SIZE CURR (MN),FINAL CLOSE SIZE CURR (MN)
count,426028.000000,426028.000000,426028.000000,410921.000000,426028,4.260280e+05,4.260280e+05,4.260280e+05,4.260280e+05,376084.000000,287896.000000,410921.00000
mean,35045.270778,30544.065472,2009.460458,1270.622988,2015-03-25 02:19:55.865060352,2.574059e+06,-7.292431e+06,4.885748e+06,-2.406684e+06,2.481823,1476.167225,1373.36687
min,3.000000,2.000000,1982.000000,0.100000,1982-11-09 00:00:00,-1.935000e+07,-6.405030e+07,-8.885541e+03,-3.405980e+07,1.000000,0.100000,0.10000
25%,6097.000000,479.000000,2005.000000,233.000000,2011-02-14 00:00:00,-6.808892e-02,-9.810000e+06,2.591259e+04,-6.000000e+06,2.000000,300.000000,243.10000
50%,18031.000000,1886.000000,2010.000000,505.000000,2016-08-15 00:00:00,5.100112e+05,-8.388100e+06,1.591468e+06,-3.513575e+06,2.000000,600.000000,518.70000
75%,53676.000000,12961.000000,2015.000000,1215.000000,2020-09-30 00:00:00,4.447079e+06,-4.766000e+06,7.633000e+06,-8.029050e+05,3.000000,1500.000000,1272.90000
max,226688.000000,727870.000000,2024.000000,30400.000000,2025-03-31 00:00:00,1.020111e+09,0.000000e+00,2.045216e+08,1.945216e+08,4.000000,390000.000000,390000.00000
std,38762.888030,83053.007817,7.464999,2282.478572,NaN,4.662843e+06,3.379617e+06,7.840453e+06,6.812181e+06,1.074829,4804.298174,4239.70620

In [6]:
funds = pd.read_excel('Funds.xlsx')

In [7]:
funds.describe()

,FUND ID,FIRM ID,FUND SERIES ID,VINTAGE / INCEPTION YEAR,FUND SIZE (USD MN),DATE ADDED,FUND NUMBER (OVERALL),FUND NUMBER (SERIES),LIFESPAN (YEARS),TARGET IRR - NET MIN,...,OPEN END RETURNS YTD(%),OPEN END RETURNS - 2 YEARS(% P.A.),OPEN END RETURNS - 3 YEARS(% P.A.),OPEN END RETURNS - 5 YEARS(% P.A.),OPEN END RETURNS - 10 YEARS(% P.A.),OPEN ENDED VALUATIONS - AS AT DATE,OPEN ENDED VALUATIONS - NAV (MN),OPEN ENDED VALUATIONS - GAV (MN),FUND MANAGER TOTAL AUM (USD MN),FUND MANAGER TOTAL AUM (EUR MN)
count,109713.000000,109713.000000,45385.000000,109679.000000,80987.000000,109713,97360.000000,88635.000000,15125.000000,7354.000000,...,200.00000,27.000000,357.000000,266.000000,88.000000,1091,946.000000,671.000000,6.244800e+04,6.244800e+04
mean,121126.745718,194099.671033,12328.173119,2016.780350,305.490814,2019-05-07 20:58:06.161940224,13.443057,2.410707,8.562493,13.834542,...,3.48675,8.184444,4.266090,4.947596,8.423544,2023-03-20 02:06:42.566452480,1815.330297,3823.274809,1.021754e+05,9.407337e+04
min,2.000000,1.000000,4.000000,1969.000000,0.000000,2004-05-14 16:47:37,1.000000,1.000000,0.300000,0.000000,...,-15.48000,-3.810000,-44.450000,-21.200000,-6.530000,2005-09-30 00:00:00,0.140000,0.890000,0.000000e+00,0.000000e+00
25%,67780.000000,14971.000000,4452.000000,2014.000000,16.900000,2016-11-30 20:00:09,1.000000,1.000000,6.000000,10.000000,...,0.57250,3.650000,-0.100000,1.900000,4.122500,2022-09-30 00:00:00,120.275000,203.000000,5.540000e+02,5.064800e+02
50%,128453.000000,151146.000000,9053.000000,2019.000000,66.590000,2021-04-19 04:43:46,3.000000,1.000000,8.000000,13.000000,...,2.81500,8.520000,5.310000,4.710000,7.010000,2024-09-30 00:00:00,360.717000,602.000000,2.421830e+03,2.228750e+03
75%,176801.000000,313210.000000,14571.000000,2022.000000,229.200000,2023-08-11 02:40:10,8.000000,2.000000,10.000000,17.000000,...,6.60750,10.580000,8.440000,7.979450,9.925000,2024-12-31 00:00:00,1249.863771,2181.650000,1.580278e+04,1.461504e+04
max,232316.000000,739103.000000,46534.000000,2026.000000,98583.000000,2025-04-28 16:08:43,1075.000000,186.000000,100.000000,100.000000,...,33.26000,35.980000,35.040000,72.230000,59.100000,2025-03-31 00:00:00,153493.000000,376900.000000,1.158393e+07,1.070225e+07
std,67440.063405,187862.209740,11402.601950,7.259228,1111.650275,NaN,69.843892,5.339673,4.711603,6.220582,...,5.51374,7.739799,8.153366,7.249186,8.440475,NaN,7013.864665,21128.668294,6.317398e+05,5.717097e+05

In [9]:
print("funds")
print(funds.columns.tolist())

funds
['FUND ID', 'FIRM ID', 'FUND SERIES ID', 'NAME', 'VINTAGE / INCEPTION YEAR', 'ASSET CLASS', 'STRATEGY', 'PRIMARY REGION FOCUS', 'STATUS', 'FUND SIZE (USD MN)', 'FUND MANAGER', 'FUND STRUCTURE', 'DOMICILE', 'DATE ADDED', 'FUND LEGAL STRUCTURE', 'FUND NUMBER (OVERALL)', 'FUND NUMBER (SERIES)', 'FUND SERIES NAME', 'SINGLE DEAL FUND', 'CONTINUATION FUND', 'LINKED CONTINUATION FUND', 'LIFESPAN (YEARS)', 'LIFESPAN EXTENSION', 'SOLELY FINANCED BY', 'TARGET IRR - NET MIN', 'TARGET IRR - NET MAX', 'TARGET IRR - GROSS MIN', 'TARGET IRR - GROSS MAX', 'FUND CURRENCY', 'TARGET SIZE (CURR. MN)', 'TARGET SIZE (USD MN)', 'TARGET SIZE (EUR MN)', 'INITIAL TARGET (CURR. MN)', 'INITIAL TARGET (USD MN)', 'INITIAL TARGET (EUR MN)', 'HARD CAP (CURR. MN)', 'HARD CAP (USD MN)', 'HARD CAP (EUR MN)', 'FUND RAISING LAUNCH DATE', 'LATEST CLOSE DATE', 'LATEST INTERIM CLOSE DATE', 'LATEST INTERIM CLOSE SIZE (CURR. MN)', 'LATEST INTERIM CLOSE SIZE (USD MN)', 'LATEST INTERIM CLOSE SIZE (EUR MN)', 'FINAL CLOSE DATE', 'FINAL CLOSE SIZE (CURR. MN)', 'FINAL CLOSE SIZE (USD MN)', 'FINAL CLOSE SIZE (EUR MN)', 'OFFER CO-INVESTMENT OPPORTUNITIES TO LPS?', 'CO-INVESTMENT CAPITAL AMOUNT (CURR. MN)', 'CO-INVESTMENT CAPITAL AMOUNT (USD MN)', 'CO-INVESTMENT CAPITAL AMOUNT (EUR MN)', 'MONTHS TO FIRST CLOSE', 'MONTHS IN MARKET', 'CORE INDUSTRIES', 'INDUSTRIES', 'INDUSTRY VERTICALS', 'PE: BUYOUT FUND LEVERAGE (%)', 'PE: BUYOUT FUND SIZE', 'PE: INVESTMENT SIZE PER PORTFOLIO COMPANY (MIN)', 'PE: INVESTMENT SIZE PER PORTFOLIO COMPANY (MAX)', 'PE: FOF FUND PREFERENCES', 'RE: PRIMARY STRATEGY', 'RE: OTHER STRATEGIES', 'RE: MAIN PROPERTY TYPE', 'RE: PROPERTY TYPES', 'RE: DEBT TYPES', 'RE: TARGET LEVERAGE (UPPER RANGE)', 'RE: TARGET LEVERAGE (LOWER RANGE)', 'RE: MAXIMUM LEVERAGE', 'INF: PRIMARY STRATEGY', 'INF: STRATEGIES', 'INF: PROJECT STAGE', 'INF: PRIMARY SECTOR', 'INF: INFRASTRUCTURE INDUSTRY PREFERENCES', 'INF: PPP/PFI INVESTMENTS', 'PD: PRIMARY DIRECT LENDING STRATEGY', 'PD: TYPE OF DEBT ISSUED', 'PD: BDC', 'PD: TRANSACTION TYPES', 'PD: DEBT SOURCING', 'PD: USES OF DEBT', 'PD: EQUITY PARTICIPATION', 'PD: LEVERAGE USED (X) MIN', 'PD: LEVERAGE USED (X) MAX', 'PD: LEVERAGE USED', 'NR: PRIMARY NATURAL RESOURCES STRATEGY', 'NR: MLP', 'NR: NATURAL RESOURCES PREFERENCES', 'NR: AGRICULTURE/FARMLAND PREFERENCES', 'NR: ENERGY PREFERENCES', 'NR: METALS AND MINING PREFERENCES', 'NR: TIMBERLAND PREFERENCES', 'NR: WATER PREFERENCES', 'NR: STRATEGY ALLOCATION', 'NR: PROJECT/ASSET STAGE', 'NR: DEBT STRATEGIES', 'PLACEMENT AGENTS', 'LAW FIRMS', 'MGMT FEE RATE (%) DURING INV PERIOD', 'CHARGE FREQUENCY', 'INVESTMENT PERIOD (YRS)', 'MECHANISM FOR MGMT FEE REDUCTIONS - POST-INVESTMENT PERIOD', 'MGMT FEE RATE (%) - POST-INVESTMENT PERIOD', 'SPECIAL PROVISION FOR LARGER LPS', 'CARRIED INTEREST (%)', 'CARRIED INTEREST BASIS', 'GP CATCH UP RATE (%)', 'HURDLE RATE (%)', 'KEY MAN CLAUSE', 'SHARE OF TRANSACTION FEES REBATED TO LP (%)', 'NO-FAULT DIVORCE CLAUSE?', 'LP MAJORITY REQUIRED (%)', 'FUND FORMATION COSTS (MN)', 'ADVISORY BOARD LP\xa0 REPRESENTATION', 'GP COMMITMENTS TO FUND (% OF TOTAL)', 'NUMBER OF LPS (MIN)', 'NUMBER OF LPS (MAX)', 'PERCENTAGE OF RETURNING LPS', 'REGION', 'ADDRESS', 'CITY', 'STATE', 'ZIP CODE', 'COUNTRY', 'WEBSITE', 'EMAIL', 'TEL', 'FAX', 'SECONDARY LOCATIONS', 'ESTIMATED LAUNCH', 'GEOGRAPHIC FOCUS', 'AUDITORS', 'ADMINISTRATORS', 'PRIME BROKERS', 'CUSTODIANS', 'OTHER GEOGRAPHIES', 'SUBSCRIPTION CREDIT FACILITY', 'GEOGRAPHIC EXPOSURE', 'OPEN END RETURNS - AS AT DATE', 'OPEN END RETURNS - 1 MONTH(%)', 'OPEN END RETURNS - 3 MONTHS(%)', 'OPEN END RETURNS - 6 MONTHS(%)', 'OPEN END RETURNS - 9 MONTHS(%)', 'OPEN END RETURNS - 12 MONTHS(%)', 'OPEN END RETURNS YTD(%)', 'OPEN END RETURNS - 2 YEARS(% P.A.)', 'OPEN END RETURNS - 3 YEARS(% P.A.)', 'OPEN END RETURNS - 5 YEARS(% P.A.)', 'OPEN END RETURNS - 10 YEARS(% P.A.)', 'OPEN ENDED VALUATIONS - AS AT DATE', 'OPEN ENDED VALUATIONS - NAV (MN)', 'OPEN ENDED VALUATIONS - GAV (MN)', 'OPEN ENDED VALUATIONS - CURRENCY', 'PRIVATE WEALTH', 'SEMI-LIQUID STRUCTURE', 'ESG FUND LABEL', 'FUND MANAGER TOTAL AUM (CURR MN)', 'FUND MANAGER TOTAL AUM (USD MN)', 'FUND MANAGER TOTAL AUM (EUR MN)']